resources:
  - resources/base.yaml

debug:
  password: "1234567890"

gid-client-http:
  base_url: "http://localhost:8080/gid/grpc-web"
  service_name: "gid"

gid-client:
  service:
    addr: localhost:50051
    name: gid

