resources:
  - resources/grpc.yaml

debug:
  password: "1234567890"

app:
  addr: ":8080"
  debug: true

gid-client-http:
  base_url: "http://localhost:8080/gid/grpc-web"
  service_name: "gid"

gid-client:
  service:
    addr: localhost:50051
    name: gid

logger:
  level: debug
  as_json: false

metric:
  driver: "prometheus"
  interval: 5s

grpc_server:
  enable_print_routes: true
  enable_cors: true
  ws_read_limit: 10
#  http_port: 8081
#  grpc_port: 50052

#task:
#  http_port: 8081
